INSERT INTO Productos(nombre, descripcion, precio, categoria_id)
VALUES ('Central Park', 'Blend de carne x2, Cheddar x4, Aderezo y Pan Standburg', 9400, 1),
	   ('Central Park Simple', 'Blend de carne x1, Cheddar x2, Aderezo y Pan Standburg', 8400, 1),
	   ('Time Square (Cheese Bacon)', 'Blend de carne x2, Cheddar x4, Bacon x2, Aderezo Time Square, Pan Standburg', 9800, 1),
	   ('STANDBURG', 'Blend de carne x2, Cheddar x2, Dambo x2, Bacon x2, Cebolla caramelizada, Aderezo y Pan Standburg', 10400, 1),
	   ('Wall Street', 'Blend de carne x2, Cheddar x4, Bacon x2, Cebolla Crispy, Aderezo Time, Pan Standburg', 10200, 1),
	   ('York Street', 'Blend de carne x2, Smasheado con cebolla, Cheddar x2, Pan Standburg', 9900, 1),
	   ('Green Point Avenue (Veggie)', 'Medallon veggie x1, Dambo x2, Coleslow, Pepinillos encurtidos, Cebolla morada, Aderezo y Pan Standburg', 8900, 1),
	   ('BROOKLYN', 'Blend de carne x2, Cheddar x4, Lechuga, Tomate, Cebolla morada, Ali Oli, Pan Standburg', 9500, 1),
	   ('Harlem+', 'Pollo crispy x2, Dambo x4, Pepinnilos encurtidos, Cebolla morada, Coleslaw, Aderezo Chick-Fil-A, Pan Standburg', 9200, 1),
	   ('BROADWAY', 'Blend de carne x2, Dambo x4, Lechuga, Tomate, Pepinnilos encurtidos, Cebolla morada, Aderezo Ranch, Pan Standburg', 10400, 1),
	   ('Ensalada Cesar', 'Crutones, Pollo Crispy, Lechuga repollada, Salsa Caesar y Queso parmesano', 8000, 5),
	   ('Mix de Hojas Verdes', 'Rúcula, Lechuga repollada, Tomates cherry, Queso parmesano, Mix de semillas y Aceto balsamico', 8000, 5),
	   ('Papas con cheddar y bacon STB', NULL, 8000, 4),
	   ('Papas simples STB', NULL, 5500, 4),
	   ('Fried Chicken (Crispy)', 'Porción de 240g de pollo crujiente', 8600, 4),
	   ('Blend de carne', 'Blend de carne x1', 3000, 3),
	   ('Bacon', 'Extra bacon', 2500, 3),
	   ('Pepinillos encurtidos', 'Pepinillos encurtidos', 2000, 3),
	   ('Cheddar', 'Cheddar extra en fetas', 2000, 3),
	   ('Dip de cheddar fundido', NULL, 2500, 3),
	   ('Pepsi Black', 'Pepsi Black lata 354cc', 2000, 2),
	   ('Seven-Up', 'Seven-Up lata 354cc', 2000, 2),
	   ('Agua mineral Nestle', 'Agua mineral Nestle 500cc', 2000, 2),
	   ('Stella Artois', 'Stella Artois 330cc', 3000, 2),
	   ('Pepsi', 'Pepsi 354cc', 2000, 2),
	   ('Paso de los Toros', 'Paso de los Todos lata 269cc', 2000, 2),
	   ('Mirinda', 'Mirinda lata 354cc', 2000, 2);